version: 1.0.{build}

platform:
  - x64

cache:

init:
  - git config --global core.autocrlf input

clone_script:
  - cmd: git clone --depth=1 -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
  - ps: (gc .\.gitmodules) -replace 'git@github.com:','https://github.com/' | Out-File -encoding ASCII .gitmodules
  - cmd: git submodule update --init --recursive
 

install:
  - ps: Install-Product node 7 x64
  - yarn install
  - cd draw.io/src/main/webapp
  - cat ../../extra-cache.txt >> cache.manifest
  - yarn install
  - cd ../..

before_build:

build_script:
  - yarn run sync
  - yarn run release

test: off
