name: Electron Builder CI (WIN)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout reposistory
      uses: actions/checkout@v3
    - name: Installing Node
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Prepare for Windows Build
      shell: powershell #The default shell for Windows
      run: |
        git config --global core.autocrlf input
        (gc .\.gitmodules) -replace 'git@github.com:','https://github.com/' | Out-File -encoding ASCII .gitmodules
        git submodule update --init --recursive
        npm install -g yarn
        yarn install
    - name: Build for Windows (x32)
      env:
        CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
        CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
      shell: powershell #The default shell for Windows
      run: |
        #Disable auto-update and build 32bit first such that latest.yml is for 64bit only (64bit will overwrite 32bit one)
        yarn run sync disableUpdate
        yarn run release-win32
    - name: Build for Windows (x64)
      env:
        CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
        CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
      shell: powershell #The default shell for Windows
      run: |
        #Enable auto-update again
        yarn run sync
        yarn run release-win
    - name: Build for Windows (APPX)
      shell: powershell #The default shell for Windows
      run: |
        #Disable auto-update for appx also
        yarn run sync disableUpdate
        yarn run release-appx
