name: Electron Builder CI (WIN)

on:
  push:
    branches:
      - dev
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout reposistory
      uses: actions/checkout@v2
    - name: Installing Node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Build for Windows
      shell: powershell #The default shell for Windows
      run: |
        git config --global core.autocrlf input
        (gc .\.gitmodules) -replace 'git@github.com:','https://github.com/' | Out-File -encoding ASCII .gitmodules
        git submodule update --init --recursive
        npm install -g yarn
        yarn install
        cd drawio/src/main/webapp
        yarn install
        cd ../..
        #Disable auto-update and build 32bit first such that latest.yml is for 64bit next
        yarn run sync disableUpdate
        yarn run release-win32
        #Enable auto-update again
        yarn run sync
        yarn run release-win
        #Disable auto-update for appx also
        yarn run sync disableUpdate
        yarn run release-appx
